version: "3.9"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env.prod
    command: gunicorn -k uvicorn.workers.UvicornWorker -w 4 \
             backend.app.main:app --bind 0.0.0.0:8000
    depends_on: [db, redis]
    ports: ["80:8000"]
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  worker:
    build:
      context: .                # build from project root
      dockerfile: worker/Dockerfile
    env_file: .env.prod
    command: >
      celery -A worker.app.worker:celery_app worker
             --loglevel=info -Q default
    depends_on:
      - db
      - redis
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: land_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  db_data: {}
